#!/bin/bash
# Bucephalus auto/config – Mirror-Fortified (sid 2025)
lb config \
  --mode debian \
  --distribution sid \
  --architecture amd64 \
  --archive-areas "main contrib non-free non-free-firmware" \
  --bootappend-live "boot=live components persistence" \
  --linux-flavours amd64 \
  --mirror-bootstrap http://deb.debian.org/debian/ \
  --mirror-chroot http://deb.debian.org/debian/ \
  --mirror-binary http://deb.debian.org/debian/ \
  --mirror-chroot-security http://security.debian.org/debian-security/ \
  --mirror-binary-security http://security.debian.org/debian-security/ \
  --bootloader syslinux